#pragma config(Sensor, port9,  X_Gyro,         sensorVexIQ_Gyro)
#pragma config(Sensor, port11, FRC,            sensorVexIQ_LED)
#pragma config(Motor,  motor1,          RearRight,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          RearLeft,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          FrontRight,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         FrontLeft,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Abs(int x) {
	if(x < 0) return -x;
	return x;
}

int Max(int a, int b) {
	if(a > b) return a;
	return b;
}

float GyroYaw;
float RawRX;
float RawX;
float RawY;
float FieldcX;
float FieldcY;
int FL;
int FR;
int RL;
int RR;
int maxVal;

task LED()
{
	setTouchLEDColor(FRC, colorOrange);
	repeat(forever)
	{
		setTouchLEDBrightness(FRC, 100);
		sleep(750);
		setTouchLEDBrightness(FRC, 0);
		sleep(750);
	}
}

task main()
{
	resetGyro(X_Gyro);
	sleep(4000);
	startTask(LED);
	repeat (forever)
	{
		GyroYaw = getGyroHeadingFloat(X_Gyro);
		RawX = getJoystickValue(ChB);
		RawY = getJoystickValue(ChA);
		RawRX = getJoystickValue(ChC);
		FieldcX = (RawX * cosDegrees(GyroYaw)) + (RawY * sinDegrees(GyroYaw));
		FieldcY = (RawX * sinDegrees(GyroYaw)) - (RawY * cosDegrees(GyroYaw));
		FL = (FieldcY + FieldcX + RawRX);
		FR = (FieldcY - FieldcX - RawRX);
		RL = (FieldcY - FieldcX + RawRX);
		RR = (FieldcY + FieldcX - RawRX);
		maxVal = Max(Max(Abs(FL), Abs(FR)), Max(Abs(RL), Abs(RR)));
		if(maxVal > 127)
		{
			FL = (int)(FL * 127) / maxVal;
			FR = (int)(FR * 127) / maxVal;
			RL = (int)(RL * 127) / maxVal;
			RR = (int)(RR * 127) / maxVal;
		}
		setMotorSpeed(FrontLeft, FL);
		setMotorSpeed(FrontRight, FR);
		setMotorSpeed(RearLeft, RL);
		setMotorSpeed(RearRight, RR);
		if(getJoystickValue(BtnEUp) == 1)
			{
  	 	resetGyro(X_Gyro);
   		sleep(2000);
   		while(getJoystickValue(BtnEUp) == 1) sleep(20);
			}
		sleep(20);
	}
}

