#pragma config(Sensor, port9,  X_Gyro,         sensorVexIQ_Gyro)
#pragma config(Sensor, port11, FRC,            sensorVexIQ_LED)
#pragma config(Motor,  motor1,          RearRight,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          RearLeft,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          FrontRight,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         FrontLeft,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Abs(int x) {
	if(x < 0) return -x;
	return x;
}

int Max(int a, int b) {
	if(a > b) return a;
	return b;
}

float GyroYaw;
float RawRX;
float RawX;
float RawY;
float FieldcX;
float FieldcY;
float normalize;
int FL;
int FR;
int RL;
int RR;
int maxVal;


task LED()
{
	repeat(forever)
	{
		setTouchLEDBrightness(FRC, 100);
		sleep(750);
		setTouchLEDBrightness(FRC, 0);
		sleep(750);
	}
}

task main()
{
	setTouchLEDColor(FRC, colorOrange);
	setTouchLEDBrightness(FRC, 100);
	resetGyro(X_Gyro);
	sleep(4000);
	setTouchLEDBrightness(FRC, 0);
	startTask(LED);
	repeat (forever)
	{
		GyroYaw = getGyroDegreesFloat(X_Gyro);
		RawX = getJoystickValue(ChB);
		RawY = getJoystickValue(ChA);
		RawRX = getJoystickValue(ChC);

		if (Abs(RawX) < 10) RawX = 0;
		if (Abs(RawY) < 10) RawY = 0;
		if (Abs(RawRX) < 10) RawRX = 0;

		FieldcX = (RawX * cosDegrees(GyroYaw)) - (RawY * sinDegrees(GyroYaw));
		FieldcY = (RawY * cosDegrees(GyroYaw)) + (RawX * sinDegrees(GyroYaw));

		FL = (int)(FieldcY + FieldcX + RawRX);
		FR = (int)(FieldcY - FieldcX - RawRX);
		RL = (int)(FieldcY - FieldcX + RawRX);
		RR = (int)(FieldcY + FieldcX - RawRX);

		maxVal = Max(Max(Max(Abs(FL), Abs(FR)), Max(Abs(RL), Abs(RR))), 1);

		normalize = (127.0 / maxVal);

		setMotorSpeed(FrontLeft, (int)(FL * normalize));
		setMotorSpeed(FrontRight, (int)(FR * normalize));
		setMotorSpeed(RearLeft, (int)(RL * normalize));
		setMotorSpeed(RearRight, (int)(RR * normalize));

		if(getJoystickValue(BtnEUp) == 1)
			{
				stopTask(LED);
				setTouchLEDBrightness(FRC, 100);
  	 		resetGyro(X_Gyro);
   			sleep(2000);
   			setTouchLEDBrightness(FRC, 0);
   			startTask(LED);
   			while(getJoystickValue(BtnEUp) == 1) sleep(20);
			}
		sleep(20);
	}
}
