#pragma config(Sensor, port9,  X_Gyro,         sensorVexIQ_Gyro)
#pragma config(Sensor, port11, FRC,            sensorVexIQ_LED)
#pragma config(Motor,  motor1,          RearRight,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          RearLeft,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          FrontRight,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         FrontLeft,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float GyroYaw;
float RawRX;
float RawX;
float RawY;
float FieldcX;
float FieldcY;
int FL;
int FR;
int RL;
int RR;

task Recalib()
{
	resetGyro(X_Gyro);
  sleep(2000);
  while(getJoystickValue(BtnEUp) == 1) sleep(20);
}

task LED()
{
	setTouchLEDColor(FRC, colorOrange);
	repeat(forever)
	{
		setTouchLEDBrightness(FRC, 100);
		sleep(750);
		setTouchLEDBrightness(FRC, 0);
		sleep(750);
	}
}

task main()
{
	resetGyro(X_Gyro);
	sleep(4000);
	startTask(LED);
	repeat (forever)
	{
		GyroYaw = getGyroHeadingFloat(X_Gyro);
		RawX = getJoystickValue(ChB);
		RawY = getJoystickValue(ChA);
		RawRX = getJoystickValue(ChC);
		FieldcX = (RawX * cosDegrees(GyroYaw)) - (RawY * sinDegrees(GyroYaw));
		FieldcY = (RawY * cosDegrees(GyroYaw)) + (RawX * sinDegrees(GyroYaw));
		FL = (FieldcY + FieldcX + RawRX);
		FR = (FieldcY - FieldcX - RawRX);
		RL = (FieldcY - FieldcX + RawRX);
		RR = (FieldcY + FieldcX - RawRX);
		setMotorSpeed(FrontLeft, FL);
		setMotorSpeed(FrontRight, FR);
		setMotorSpeed(RearLeft, RL);
		setMotorSpeed(RearRight, RR);
		if(getJoystickValue(BtnEUp) == 1)
			{
  	 	startTask(Recalib);
			}
		sleep(20);
	}
}
